name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Generate Indexes
        run: |
          chmod +x generate_indexes.sh
          ./generate_indexes.sh

      - name: Prepare Site Content
        run: |
          mkdir site
          cp -r reviews/* site/
          touch site/.nojekyll
          echo "Files in site/:"
          ls -R site | head -n 20

      - name: Fix LFS URLs
        run: |
          python3 fix_lfs_urls.py site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
